---
- name: Configure DNS server
  hosts: dnsservers
  gather_facts: no
  sudo_user: root
  sudo: true

  #https://blog.bigdinosaur.org/running-bind9-and-isc-dhcp/
  
  vars:
    dnsfowarders: "XXX.XXX.XXX.XXX;XXX.XXX.XXX.XXX;"

  tasks:

    - name: install bind9
      apt: 
        name: "{{ item }}"
        state: installed 
      with_items:
      - bind9
      - bind9utils
      - bind9-host
      notify: restart bind9

    - name: copy /etc/bind/named.conf.options 
      template: src=templates/etc/bind/named.conf.options.j2 dest=/etc/bind/named.conf.options owner=root group=bind mode=644

    - name: set abc.fr in /etc/bind/named.conf.local
      copy: src=files/etc/bind/named.conf.local dest=/etc/bind/named.conf.local owner=root group=bind mode=644
      notify: restart bind9

    - name: create db.abc.fr in /etc/bind
      copy: src=files/etc/bind/db.abc.fr dest=/etc/bind/db.abc.fr owner=root group=bind mode=644
      notify: restart bind9

    - name: create db.abc.fr.rev in /etc/bind
      copy: src=files/etc/bind/db.abc.fr.rev dest=/etc/bind/db.abc.fr.rev owner=root group=bind mode=644
      notify: restart bind9

    - name: copy resolv.conf
      copy: src=files/etc/resolv.conf dest=/etc/resolv.conf owner=root group=root mode=644
      notify: restart bind9

  handlers:
    - name: restart bind9
      service: 
        name: bind9 
        state: restarted 
